/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bank_project;

import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author Krish
 */
public class Create_account_page extends javax.swing.JFrame {
    
    String otp;

    /**
     * Creates new form Create_account_page
     */
    public Create_account_page() {
        initComponents();
        buttonGroup1.add(g1);
        buttonGroup1.add(g2);
        buttonGroup1.add(g3);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        fullName1 = new javax.swing.JLabel();
        phone1 = new javax.swing.JLabel();
        email1 = new javax.swing.JLabel();
        aadharNumber1 = new javax.swing.JLabel();
        panNumber1 = new javax.swing.JLabel();
        address1 = new javax.swing.JLabel();
        fullName = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        panNumber = new javax.swing.JTextField();
        aadharNumber = new javax.swing.JTextField();
        gender = new javax.swing.JLabel();
        g1 = new javax.swing.JRadioButton();
        g2 = new javax.swing.JRadioButton();
        g3 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        fatherName1 = new javax.swing.JLabel();
        motherName1 = new javax.swing.JLabel();
        fatherName = new javax.swing.JTextField();
        motherName = new javax.swing.JTextField();
        dob = new com.toedter.calendar.JDateChooser();
        dob1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 800));
        setPreferredSize(new java.awt.Dimension(800, 800));

        fullName1.setText("ENTER FULL NAME");

        phone1.setText("PHONE NUMBER");

        email1.setText("EMAIL ID");

        aadharNumber1.setText("AADHAR NUMBER");

        panNumber1.setText("PAN NUMBER");

        address1.setText("ADDRESS");

        gender.setText("GENDER");

        g1.setText("MALE");

        g2.setText("FEMALE");

        g3.setText("OTHERS");

        address.setColumns(20);
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        fatherName1.setText("FATHER'S NAME");

        motherName1.setText("MOTHER'S NAME");

        dob1.setText("D.O.B");

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(email1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(motherName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fatherName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fullName1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(phone1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aadharNumber1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panNumber1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(address1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dob1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                            .addComponent(panNumber, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(motherName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fatherName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fullName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phone, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aadharNumber, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(133, 133, 133))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(g1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(g2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(g3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dob, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullName1)
                    .addComponent(fullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fatherName1)
                    .addComponent(fatherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motherName1)
                    .addComponent(motherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone1)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email1)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aadharNumber1)
                    .addComponent(aadharNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(panNumber1)
                    .addComponent(panNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(address1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gender)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(g1)
                        .addComponent(g2)
                        .addComponent(g3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dob1)
                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        String fullNameValue ;
        String fatherNameValue ;
        String motherNameValue ;
        String phoneValue ;
        String emailValue ;
        String aadharNumberValue ;
        String panNumberValue ;
        String addressValue ;
        String dobValue ;
        String genderValue ;
        String otpValue;
        
        
        if(fullName.getText().trim().matches("^[a-zA-Z ]+$"))
        {
        System.out.println(fullName.getText());
        fullNameValue = fullName.getText();
         fullName.setBorder(null);
            
        }
        else {
             fullName.setBorder(new LineBorder(Color.RED , 2));
            return;
         }
        
        if(fatherName.getText().trim().matches("^[a-zA-Z ]+$"))
        {
        System.out.println(fatherName.getText());
         fatherName.setBorder(null);
         fatherNameValue = fatherName.getText();
        }
        else {
             fatherName.setBorder(new LineBorder(Color.RED , 2));
            return;
         }
        
        if(motherName.getText().trim().matches("^[a-zA-Z ]+$"))
        {
        System.out.println(motherName.getText());
         motherName.setBorder(null);
         motherNameValue = motherName.getText();
        }
        else {
             motherName.setBorder(new LineBorder(Color.RED , 2));
            return;
         }
        
        
        if(phone.getText().trim().matches("^[9876]{1}[0-9]{9}"))
        {
        System.out.println(phone.getText());
         phone.setBorder(null);
         phoneValue = phone.getText();
        }
        else {
             phone.setBorder(new LineBorder(Color.RED , 2));
             return;
         }
        
        if(email.getText().trim().matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$"))
        {
        System.out.println(email.getText());
         email.setBorder(null);
         emailValue = email.getText();
        }
         else{
                email.setBorder(new LineBorder(Color.RED , 2));
                return;
            }
        
        if(aadharNumber.getText().trim().matches("^[2-9]{1}[0-9]{11}$"))
        {
        System.out.println(aadharNumber.getText());
         aadharNumber.setBorder(null);
         aadharNumberValue = aadharNumber.getText();
        }
         else{
                aadharNumber.setBorder(new LineBorder(Color.RED , 2));
                return;
            }
        
        if(panNumber.getText().trim().matches("^[A-Z]{5}[0-9]{4}[A-Z]{1}$"))
        {
        System.out.println(panNumber.getText());
         panNumber.setBorder(null);
         panNumberValue = panNumber.getText();
        }
         else{
                panNumber.setBorder(new LineBorder(Color.RED , 2));
                return;
            }
        
        if(!address.getText().trim().equalsIgnoreCase(""))
        {
        System.out.println(address.getText());
         address.setBorder(null);
         addressValue = address.getText();
         
        }
         else{
                address.setBorder(new LineBorder(Color.RED , 2));
                return;
            }
         
        if( !dob.getCalendar().getTime().toString().equalsIgnoreCase(""))
        {
        System.out.println( dob.getCalendar().getTime().toString());
        dobValue = dob.getCalendar().getTime().toString();
         
        }
         else
         {
                JOptionPane.showMessageDialog(this, "ENTER YOUR DOB");
                return;
            }
        
       
                
         genderValue = null;
        if(g1.isSelected()){
            genderValue = "Male";
             
            
        }
        else if(g2.isSelected()){
            genderValue = "FEMALE";
             
        }
        else if(g3.isSelected()){
            genderValue = "Others";
            
        }
        else{
            JOptionPane.showMessageDialog(this, "SELECT GENDER");
            return;
        }
        
         String phoneNumber = phone.getText();
        otp = Smssender.getOtp();
        Smssender.sendSms(phoneNumber, " HI. WE ARE FROM BANK. YOUR OTP FOR VERIFICATION IS " +otp);
        otpValue = otp;
        this.setVisible(false);
        new otp_password(fullNameValue,fatherNameValue,motherNameValue,phoneValue,emailValue,aadharNumberValue,panNumberValue,addressValue,dobValue,genderValue,otpValue).setVisible(true);
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Create_account_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Create_account_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Create_account_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create_account_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Create_account_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aadharNumber;
    private javax.swing.JLabel aadharNumber1;
    private javax.swing.JTextArea address;
    private javax.swing.JLabel address1;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JLabel dob1;
    private javax.swing.JTextField email;
    private javax.swing.JLabel email1;
    private javax.swing.JTextField fatherName;
    private javax.swing.JLabel fatherName1;
    private javax.swing.JTextField fullName;
    private javax.swing.JLabel fullName1;
    private javax.swing.JRadioButton g1;
    private javax.swing.JRadioButton g2;
    private javax.swing.JRadioButton g3;
    private javax.swing.JLabel gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField motherName;
    private javax.swing.JLabel motherName1;
    private javax.swing.JTextField panNumber;
    private javax.swing.JLabel panNumber1;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel phone1;
    // End of variables declaration//GEN-END:variables
}
