/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bank_project;

import javax.swing.JTextField;

/**
 *
 * @author Krish
 */


public class Features extends javax.swing.JFrame {
    
    /**
     * Creates new form Features
     */
    
    int accountnumber;
    
     public Features() {
        initComponents();
    }
    public Features(String accountnumbervalue) {
       this();
        accountnumber = Integer.valueOf(accountnumbervalue);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMoney = new javax.swing.JButton();
        withdrawMoney = new javax.swing.JButton();
        sendMoney = new javax.swing.JButton();
        viewTransactionHistory = new javax.swing.JButton();
        viewBalance = new javax.swing.JButton();
        updateDetails = new javax.swing.JButton();
        changePassword = new javax.swing.JButton();
        closeBankAccount = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 800));
        setPreferredSize(new java.awt.Dimension(800, 800));

        addMoney.setText("ADD MONEY");
        addMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMoneyActionPerformed(evt);
            }
        });

        withdrawMoney.setText("WITHDRAW MONEY");
        withdrawMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawMoneyActionPerformed(evt);
            }
        });

        sendMoney.setText("SEND MONEY");
        sendMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMoneyActionPerformed(evt);
            }
        });

        viewTransactionHistory.setText("VIEW TRANSACTION HISTORY");
        viewTransactionHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTransactionHistoryActionPerformed(evt);
            }
        });

        viewBalance.setText("VIEW BALANCE");
        viewBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBalanceActionPerformed(evt);
            }
        });

        updateDetails.setText("UPDATE DETAILS");
        updateDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDetailsActionPerformed(evt);
            }
        });

        changePassword.setText("CHANGE PASSWORD");
        changePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordActionPerformed(evt);
            }
        });

        closeBankAccount.setText("CLOSE BANK ACCOUNT");
        closeBankAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBankAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(withdrawMoney, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addMoney, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sendMoney, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewTransactionHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(viewBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(changePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(closeBankAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(addMoney)
                .addGap(18, 18, 18)
                .addComponent(withdrawMoney)
                .addGap(18, 18, 18)
                .addComponent(sendMoney)
                .addGap(18, 18, 18)
                .addComponent(viewTransactionHistory)
                .addGap(18, 18, 18)
                .addComponent(viewBalance)
                .addGap(18, 18, 18)
                .addComponent(updateDetails)
                .addGap(18, 18, 18)
                .addComponent(changePassword)
                .addGap(18, 18, 18)
                .addComponent(closeBankAccount)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMoneyActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Add_money(accountnumber ).setVisible(true);
        
    }//GEN-LAST:event_addMoneyActionPerformed

    private void withdrawMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawMoneyActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Withdraw_money(accountnumber).setVisible(true);
    }//GEN-LAST:event_withdrawMoneyActionPerformed

    private void sendMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMoneyActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Send_recieve_money(accountnumber).setVisible(true);
    }//GEN-LAST:event_sendMoneyActionPerformed

    private void viewTransactionHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTransactionHistoryActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        new Transaction_history(accountnumber).setVisible(true);
    }//GEN-LAST:event_viewTransactionHistoryActionPerformed

    private void viewBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBalanceActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        new View_Balance(accountnumber).setVisible(true);
    }//GEN-LAST:event_viewBalanceActionPerformed

    private void updateDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDetailsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Update_account_details(accountnumber).setVisible(true);
    }//GEN-LAST:event_updateDetailsActionPerformed

    private void changePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        new Change_password(accountnumber).setVisible(true);
    }//GEN-LAST:event_changePasswordActionPerformed

    private void closeBankAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBankAccountActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        new Close_account(accountnumber).setVisible(true);
    }//GEN-LAST:event_closeBankAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Features.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Features.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Features.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Features.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMoney;
    private javax.swing.JButton changePassword;
    private javax.swing.JButton closeBankAccount;
    private javax.swing.JButton sendMoney;
    private javax.swing.JButton updateDetails;
    private javax.swing.JButton viewBalance;
    private javax.swing.JButton viewTransactionHistory;
    private javax.swing.JButton withdrawMoney;
    // End of variables declaration//GEN-END:variables
}
